name: Publish

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        with:
          ref: 'main'
      
      - name: Update docs content
        run: |
          git submodule init
          git submodule update --remote

      - name: Setup website by docs content
        run: node setup.js

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PWD}}

      - name: Generate docker image tag name
        id: generate-tag-name
        run: |
          export tag=${{ github.sha }}-$GITHUB_RUN_NUMBER
          echo $tag
          echo "::set-output name=docker_tag::$tag"

      - name: Build and push image to Harbor
        id: build-image
        run: |
          docker build -t tumao/towhee-docs-web:${{ steps.generate-tag-name.outputs.docker_tag }} .
          docker push tumao/towhee-docs-web:${{ steps.generate-tag-name.outputs.docker_tag }}
